# Generated by Django 4.2 on 2024-11-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
